name = "aspiron-signature"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[r2_buckets]]
binding = "SIGNATURES"
bucket_name = "aspiron"

[vars]
R2_PUBLIC_BASE = "https://aspiron-r2.miscreants.dev"
